---
test_interval: 20
grafana_address: localhost
grafana_port: 2003
tsdb_prefix: latency
endpoints:
  - aws.amazon.com
  - cloud.google.com
  - github.com
  - a.root-servers.net
  - b.root-servers.net
  - c.root-servers.net
  - d.root-servers.net
  - e.root-servers.net
  - f.root-servers.net
  - g.root-servers.net
  - h.root-servers.net
  - i.root-servers.net
  - j.root-servers.net
  - k.root-servers.net
  - l.root-servers.net
  - m.root-servers.net
  - 8.8.8.8
  - 8.8.4.4
  
